name: eyedentify3d
channels:
  - conda-forge
dependencies:
  - python=3.11
  - biorbd=1.11.2
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pingouin
  - pytest
  - pytest-cov
  - codecov
  - black

